DBCC CHECKIDENT ('Airports',RESEED,0)
GO

INSERT INTO Airports(airportId, city, country,regionId)
VALUES
('CAN','Guangzhou','China',2),
('ATL','Atlanta, GA','United States',5),
('CTU','Chengdu','China',2),
('HND','Tokyo','Japan',2),
('DEL','Delhi','India',2),
('LAX','Los Angeles, CA','United States',5),
('IST','Arnavutköy, Istanbul','Turkey',1),
('CDG','Roissy-en-France','France',3),
('LHR','London','England',3),
('MEX','Mexico City','Mexico',4),
('SGN','Ho Chi Minh City','Vietnam',2),
('ICN','Incheon','South Korea',2),
('CJU','Jeju City','South Korea',2),
('GRU','Guarulhos','Brazil',4),
('AMS','Haarlemmermeer','Netherlands',3),
('SVO','Moscow','Russia',2),
('NKG','Nanjing','China',2),
('FRA','Frankfurt','Germany',3),
('MIA','Miami, FL','United States',5),
('GMP', 'Gangseo District','South Korea',2),
('MAD','Barajas','Spain',3),
('SAW','Pendik, Istanbul','Turkey',1),
('BKK','Bangkok','Thailand',2),
('JFK','New York, NY','United States',5),
('DME','Domodedovo','Russia',2),
('KBL','Kabul','Afghanistan',2),
('TIA','Tirana','Albania',3),
('ALG','Algiers','Algeria',1),
('BUG','Benguela','Angola',1),
('AXA','The Valley','Anguilla',4),
('EZE','Buenos Aires','Argentina',4),
('RSA','Santa Rosa','Argentina',4),
('EVN','Yerevan','Armenia',3),
('BNE','Brisbane','Australia',2),
('CTL','Charville, Qld.','Australia',2),
('MEL','Melbourne, Vic.','Australia',2),
('SYD','Sydney, N.S.W','Australia',2),
('ZSA','Cockburn Town, San Salvador Island','Bahamas',4),
('BGI','Bridgetown','Bardados',4),
('BRU','Brussels','Belgium',3),
('LPB','La Paz','Bolivia',4),
('RIO','Rio de Janeiro',' Brazil',4),
('BWN','Bandar Seri Begawan','Brunei',2),
('SOF','Sofia','Bulgaria',3),
('PNH','Phnom Penh','Cambodia',2),
('DLA','Douala','Cameroon',1),
('YOW','Ottawa, ON','Canada',5),
('YEG','Edmonton, AB','Canada',5),
('YTO','Toronto, ON','Canada',5),
('TCI','Tenerife Island','Canary Islands',1),
('NDJ','N Djamena','Chad',1),
('ESR','El Salvador','Chile',4),
('BJS','Beijing','China',2),
('CKG','Chongqing','China',2),
('HKG','Hong Kong','China',2),
('FOC','Fuzhou','China',2),
('SHA','Shanghai','China',2),
('SJO','San Jose','Costa Rica',4),
('HAV','Havana','Cuba',4),
('CPH','Copenhagen','Denmark',3),
('POP','Puerto Plata','Dominican Republic',4),
('UIO','Quito','Ecuador',4),
('CAI','Cairo','Egypt',1),
('BRS','Bristol','England',3),
('BHX','Birmingham','England',3),
('LGW','London','England',3),
('SUV','Suva','Fiji',2),
('OUL','Oulu','Finland',3),
('VAA','Vassa','Finland',3),
('BOD','Bordeaux','France',3),
('PAR','Paris','France',3),
('CGN','Cologne','Germany',3),
('MUC','Munich','Germany',3),
('ATH','Athens','Greece',3),
('RHO','Rhodes','Greece',3),
('GUM','Agana','Guam',2),
('FRS','Flores','Guatemala',4),
('PAP','Port-au-Prince','Haiti',4),
('BUD','Budapest','Hungary',3),
('BLR','Bangalore','India',2),
('JKT','Jakarta, Java','Indonesia',2),
('THR','Tehran','Iran',2),
('DUB','Dublin','Ireland',3),
('FLR','Florence','Italy',3),
('LIN','Milan','Italy',3),
('NAP','Naples','Italy',3),
('PSA','Pisa','Italy',3),
('ROM','Rome','Italy',3),
('VCE','Venice','Italy',3),
('OCJ','Ocho Rios','Jamaica',4),
('FUK','Fukuoka','Japan',2),
('FKS','Fukushima','Japan',2),
('OSA','Osaka','Japan',2),
('KZO','Kzyl Orda','Kazakhstan',2),
('VTE','Vientiane','Laos',4),
('BEY','Beirut','Lebanon',1),
('ROB','Monrovia','Liberia',3),
('LUX','Luxembourg','Luxembourg',3),
('SKP','Skopje','Macedonia',3),
('TNR','Antananarivo','Madagascar',1),
('PXO','Port Santo','Madeira',3),
('KUL','Kuala Lumpur','Malaysia',2),
('CME','Ciudad Del Carmen','Mexico',4),
('YAP','Yap','Micronesia',2),
('CMN','Casablance','Morocco',1),
('LUA','Lukaa','Nepal',2),
('AKL','Auckland','New Zealand',2),
('ZQN','Queenstown','New Zealand',2),
('WLG','Wellington','New Zealand',2),
('LOS','Lagos','Nigeria',1),
('FNJ','Pyongyang','North Korea',2),
('BFS','Belfast','North Ireland',3),
('HFT','Hammerfest','Norway',3),
('KHI','Karachi','Pakistan',2),
('PTY','Panama City','Panama',4),
('LIM','Lima','Peru',4),
('CEB','Cebu','Philipphines',2),
('MNL','Manila','Philipphines',2),
('KRK','Krakow','Poland',3),
('KTW','Katowice','Poland',3),
('LIS','Lisbon','Portugal',3),
('SJU','San Juan','Puerto Rica',4),
('PUS','Busan','South Korea',2),
('OTP','Bucharest','Romania',3),
('LED','St. Petersburg','Russia',2),
('ABZ','Aberdeen','Scotland',3),
('EDI','Edinburgh','Scotland',3),
('DKR','Dakar','Senegal',1),
('SIN','Singapore','Singapore',2),
('CPT','Capte Town','South Africa',2),
('ALC','Alicante','Spain',3),
('BCN','Barcelona','Spain',3),
('SDR','Santander','Spain',3),
('SXM','Philipsburg','St. Maarten',3),
('MTS','Manzini','Swaziland',1),
('MMA','Malmo','Sweden',3),
('STO','Stockholm','Sweden',3),
('GVA','Geneva','Switzerland',3),
('ZRH','Zurich','Switzerland',3),
('TPE','Taipei','Taiwan',2),
('CNX','Chiang Mai','Thailand',2),
('TUN','Tunis','Tunisia',1),
('EBB','Entebbe','Uganda',1),
('KBP','Kiev','Ukraine',3),
('AUH','Abu Dhabi','United Arab Emirates',1),
('MVD','Montevideo','Uruguay',3),
('BED','Bedford, MA','United States',5),
('CHI','Chicago, IL','United States',5),
('DAL','Dallax, TX','United States',5),
('DTT','Detroit, MI','United States',5),
('HOU','Houston, TX','United States',5),
('SAN','San Diego, CA','United States',5),
('ALW','Walla Walla, WA','United States',5),
('CWL','Cardiff','Wales',3),
('SAH','Sanaa','Yemen',1),
('HRE','Harare','Zimbabwe',1)
